In [1]:
import torch 
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt


In [2]:
scalar = torch.tensor(7)

scalar.ndim #no dimensions / only one value

scalar.item() #returns scalar value as int

scalar

tensor(7)

In [3]:
vector = torch.tensor([[7,8],[6,9]])
vector.ndim # 1
vector.shape 

torch.Size([2, 2])

In [4]:
vals = torch.arange(0,11)
vals

val_zeros = torch.zeros_like(input = vals)
val_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
tensor_float_32 = torch.tensor([1,2,42,44.9999])

tensor_float_16 = tensor_float_32.type(torch.int32)

tensor_float_32 * tensor_float_16

tensor([1.0000e+00, 4.0000e+00, 1.7640e+03, 1.9800e+03])

In [6]:
tensor_int_16 = torch.tensor([12,343,222,1],dtype = torch.int16)
tensor_int_16 * tensor_float_32

tensor([  12.0000,  686.0000, 9324.0000,   44.9999])

In [7]:
tensor = torch.arange(1,100)

In [8]:
%%time
def multi(mat1,mat2):
    sum = 0 
    for i in range(len(mat1)):
        sum += mat1[i] * mat2[i]
    
    return sum

multi(tensor,tensor)

CPU times: user 1.5 ms, sys: 918 µs, total: 2.42 ms
Wall time: 7.7 ms


tensor(328350)

In [9]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 595 µs, sys: 0 ns, total: 595 µs
Wall time: 1.83 ms


tensor(328350)

In [10]:
%%time
tensor_a = torch.tensor([[1,2],
                        [3,4],
                        [7,8]])
tensor_b = torch.tensor([[8,9],
                        [10,11],
                        [12,13]])

torch.mm(tensor_a , tensor_b.T)

CPU times: user 1.05 ms, sys: 0 ns, total: 1.05 ms
Wall time: 5.43 ms


tensor([[ 26,  32,  38],
        [ 60,  74,  88],
        [128, 158, 188]])

In [11]:
x = torch.tensor([1,2,3,4,5,6,7,8,9,10])
x.dtype

torch.mean(x.type(torch.float32))
x = x.type(torch.float32)

x *= 10
x.argmax()

tensor(9)

In [12]:
x_res = x.reshape([1,10])
x_res = x_res.squeeze()
x_res.unsqueeze(dim = 0)

tensor([[ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.]])

In [13]:
y = (1,0,2)

x = torch.randn(2,3,5)
x.size()

x = x.permute(dims=y) # change in dimensions
x.size()

torch.Size([3, 2, 5])

In [14]:
colors = torch.rand(size=(224,224,3))
colors_per = colors.permute(2,0,1) #different view same memory space as original vector
colors_per.size()
colors.size()

colors[0,0,0] = 434374
colors_per[0,0,0] = 8888

print(f"{colors[0,0,0]} : {colors_per[0,0,0]}")

8888.0 : 8888.0


In [15]:
val = torch.arange(1,11).reshape(2,1,5)
val[:,:,2]

tensor([[3],
        [8]])

In [16]:
rand_seed = 1
torch.manual_seed(rand_seed)
tensor_c = torch.rand(3,4)

torch.manual_seed(rand_seed)
tensor_d = torch.rand(3,4)

print(f"tensor_c : {tensor_c} , tensor_d : {tensor_d}" , {tensor_c == tensor_d})


tensor_c : tensor([[0.7576, 0.2793, 0.4031, 0.7347],
        [0.0293, 0.7999, 0.3971, 0.7544],
        [0.5695, 0.4388, 0.6387, 0.5247]]) , tensor_d : tensor([[0.7576, 0.2793, 0.4031, 0.7347],
        [0.0293, 0.7999, 0.3971, 0.7544],
        [0.5695, 0.4388, 0.6387, 0.5247]]) {tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])}


In [17]:
#gpu tensors cannot be converted to numpy arrays convert to cpu first / host memory

In [18]:
rand_tensor = torch.rand(7,7)
rand_tensor
rand_tensor.size()

torch.Size([7, 7])

In [19]:
rand_tensor_2 = torch.rand(1,7)

rand_matmul = torch.matmul(rand_tensor,rand_tensor_2.T)
rand_matmul

tensor([[2.3658],
        [1.6567],
        [2.6875],
        [1.1844],
        [2.5899],
        [1.9480],
        [2.7917]])

In [20]:
rand_seed = 0 

torch.manual_seed(rand_seed)
rand_tensor = torch.rand(7,7)

torch.manual_seed(rand_seed)
rand_tensor_2 = torch.rand(1,7)


rand_matmul = torch.matmul(rand_tensor,rand_tensor_2.T)
rand_matmul

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [22]:
torch.cuda.manual_seed(1234)

In [55]:
torch.manual_seed(1234)
r_ten1 = torch.rand([2,3],device ='cuda')
r_ten2 = torch.rand([2,3],device ='cuda')

print(f"device of tensors 1 & 2 : {r_ten1.device,r_ten2.device}")

mul = torch.matmul(r_ten1,r_ten2.T)

mul


device of tensors 1 & 2 : (device(type='cuda', index=0), device(type='cuda', index=0))


tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')

In [73]:
mul.mean() , mul.max()

(tensor(0.5975, device='cuda:0'), tensor(0.7668, device='cuda:0'))

In [60]:
mul.argmin() , mul.argmax()

(tensor(0, device='cuda:0'), tensor(1, device='cuda:0'))

In [72]:
torch.manual_seed(7)
rand = torch.rand(1,1,1,10)
rand_edit = rand.squeeze()
rand_edit.size()
print(f"rand : {rand} , shape : {rand.size()}")
print(f"rand_edit : {rand_edit} , shape : {rand_edit.size()}")

rand : tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) , shape : torch.Size([1, 1, 1, 10])
rand_edit : tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) , shape : torch.Size([10])
